### Hello World
GET / HTTP/1.1
Host: localhost:3333

### Create user - Body params
POST /users HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
    "name": "maicon",
    "email": "maicon@gmail.com"
}


### Get users
GET /users HTTP/1.1
Host: localhost:3333
Content-Type: application/json

### Get user - request param
GET /users/2 HTTP/1.1
Host: localhost:3333
Content-Type: application/json


### Get users - Query params
GET /users?search=on HTTP/1.1
Host: localhost:3333
Content-Type: application/json
