### List items
GET /items HTTP/1.1
Host: localhost:3333
Content-Type: application/json

### Create collect point
POST /points HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "name": "Mercado Rony",
  "email": "rony@contato.com",
  "whatsapp": "41998451597",
  "latitude": -45.11234,
  "longitude": -86.235,
  "city": "Sao Jose dos Pinhais",
  "uf": "PR",
  "items": [
    1,
    2,
    6
  ]
}

### List point
GET /points/6 HTTP/1.1
Host: localhost:3333
Content-Type: application/json

### List filtered points
GET /points?city=Curitiba&uf=PR&items=1,2 HTTP/1.1
Host: localhost:3333
Content-Type: application/json
